-- ============================================================
-- FotoGPS — Esquema PostgreSQL (Supabase)
-- Estado consolidado: equivale a schema.sql + v2..v20 de MySQL
--
-- Ejecutar en Supabase SQL Editor (Settings > SQL Editor)
-- ============================================================

-- -----------------------------------------------------------
-- Trigger reutilizable para updated_at
-- -----------------------------------------------------------
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------
-- 1. EMPRESAS
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS empresas (
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                  VARCHAR(200) NOT NULL,
    formato_nombre_foto     SMALLINT NOT NULL DEFAULT 1,
    op_mostrar_empresa      SMALLINT NOT NULL DEFAULT 0,
    op_mostrar_infraestructura SMALLINT NOT NULL DEFAULT 0,
    op_mostrar_situacion    SMALLINT NOT NULL DEFAULT 0,
    op_mostrar_mapa         SMALLINT NOT NULL DEFAULT 0,
    op_mapa_zoom            SMALLINT NOT NULL DEFAULT 9,
    op_mostrar_capas_infra  SMALLINT NOT NULL DEFAULT 0,
    plan_suscripcion        VARCHAR(20) NOT NULL DEFAULT 'free'
                            CHECK (plan_suscripcion IN ('free','basic','professional','enterprise')),
    nif                     VARCHAR(20) DEFAULT NULL,
    email_contacto          VARCHAR(255) DEFAULT NULL,
    activa                  SMALLINT NOT NULL DEFAULT 1,
    licencia_inicio         DATE DEFAULT NULL,
    licencia_fin            DATE DEFAULT NULL,
    max_usuarios            INT NOT NULL DEFAULT 10,
    max_infraestructuras    INT NOT NULL DEFAULT 50,
    logo_url                VARCHAR(512) DEFAULT NULL,
    wm_mostrar_fecha        SMALLINT NOT NULL DEFAULT 1,
    wm_mostrar_coordenadas  SMALLINT NOT NULL DEFAULT 1,
    wm_mostrar_orientacion  SMALLINT NOT NULL DEFAULT 1,
    wm_mostrar_ubicacion    SMALLINT NOT NULL DEFAULT 1,
    wm_mostrar_pais         SMALLINT NOT NULL DEFAULT 1,
    wm_mostrar_brujula      SMALLINT NOT NULL DEFAULT 1,
    wm_mostrar_codigo_infra SMALLINT NOT NULL DEFAULT 0,
    wm_mostrar_situacion    SMALLINT NOT NULL DEFAULT 0,
    wm_mostrar_tipo_foto    SMALLINT NOT NULL DEFAULT 0,
    wm_mostrar_mapa         SMALLINT NOT NULL DEFAULT 0,
    wm_mapa_zoom            SMALLINT NOT NULL DEFAULT 15,
    wm_mapa_tamano          SMALLINT NOT NULL DEFAULT 2,
    wm_texto_tamano         SMALLINT NOT NULL DEFAULT 2,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_empresas_plan ON empresas (plan_suscripcion);
CREATE INDEX IF NOT EXISTS idx_empresas_activa ON empresas (activa);

CREATE TRIGGER trg_empresas_updated_at
    BEFORE UPDATE ON empresas
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 2. USUARIOS
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      INT NOT NULL REFERENCES empresas (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    nombre          VARCHAR(150) NOT NULL,
    email           VARCHAR(255) DEFAULT NULL,
    telefono        VARCHAR(20) DEFAULT NULL,
    password        VARCHAR(255) NOT NULL,
    rol             VARCHAR(20) NOT NULL DEFAULT 'operador'
                    CHECK (rol IN ('superadmin','admin','supervisor','operador')),
    activo          SMALLINT NOT NULL DEFAULT 1,
    ultimo_login    TIMESTAMP DEFAULT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_email ON usuarios (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_telefono ON usuarios (telefono) WHERE telefono IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON usuarios (empresa_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios (rol);
CREATE INDEX IF NOT EXISTS idx_usuarios_empresa_rol ON usuarios (empresa_id, rol, activo);

CREATE TRIGGER trg_usuarios_updated_at
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 3. INFRAESTRUCTURAS
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS infraestructuras (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      INT NOT NULL REFERENCES empresas (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    nombre          VARCHAR(250) NOT NULL,
    codigo_unico    VARCHAR(50) NOT NULL,
    lat_teorica     DECIMAL(10,7) NOT NULL,
    lon_teorica     DECIMAL(10,7) NOT NULL,
    tipo            VARCHAR(100) DEFAULT NULL,
    provincia       VARCHAR(100) DEFAULT NULL,
    municipio       VARCHAR(150) DEFAULT NULL,
    monte           VARCHAR(200) DEFAULT NULL,
    descripcion     TEXT DEFAULT NULL,
    activa          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_infra_codigo ON infraestructuras (empresa_id, codigo_unico);
CREATE INDEX IF NOT EXISTS idx_infra_empresa ON infraestructuras (empresa_id);
CREATE INDEX IF NOT EXISTS idx_infra_coords ON infraestructuras (lat_teorica, lon_teorica);
CREATE INDEX IF NOT EXISTS idx_infra_empresa_activa ON infraestructuras (empresa_id, activa);
CREATE INDEX IF NOT EXISTS idx_infra_provincia ON infraestructuras (empresa_id, provincia);
CREATE INDEX IF NOT EXISTS idx_infra_municipio ON infraestructuras (empresa_id, provincia, municipio);
CREATE INDEX IF NOT EXISTS idx_infra_monte ON infraestructuras (empresa_id, monte);

CREATE TRIGGER trg_infraestructuras_updated_at
    BEFORE UPDATE ON infraestructuras
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 4. UNIDADES DE OBRA
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS unidades_obra (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  INT NOT NULL REFERENCES empresas (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    nombre      VARCHAR(200) NOT NULL,
    codigo      VARCHAR(50) DEFAULT NULL,
    descripcion TEXT DEFAULT NULL,
    activa      SMALLINT NOT NULL DEFAULT 1,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_uo_empresa ON unidades_obra (empresa_id);

CREATE TRIGGER trg_unidades_obra_updated_at
    BEFORE UPDATE ON unidades_obra
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 5. TIPOS DE TRABAJO
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS tipos_trabajo (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  INT NOT NULL REFERENCES empresas (id),
    nombre      VARCHAR(200) NOT NULL,
    codigo      VARCHAR(50) DEFAULT NULL,
    descripcion TEXT DEFAULT NULL,
    activa      SMALLINT NOT NULL DEFAULT 1,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tt_empresa ON tipos_trabajo (empresa_id);

CREATE TRIGGER trg_tipos_trabajo_updated_at
    BEFORE UPDATE ON tipos_trabajo
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 6. REGISTROS (inspecciones / fotos de campo)
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS registros (
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infra_id                INT NOT NULL REFERENCES infraestructuras (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    unidad_obra_id          INT DEFAULT NULL,
    tipo_trabajo_id         INT DEFAULT NULL,
    usuario_id              INT NOT NULL REFERENCES usuarios (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha                   TIMESTAMP NOT NULL DEFAULT NOW(),
    lat_real                DECIMAL(10,7) DEFAULT 0,
    lon_real                DECIMAL(10,7) DEFAULT 0,
    url_cloudinary          VARCHAR(512) DEFAULT NULL,
    datos_tecnicos          JSONB DEFAULT NULL,
    estado_incidencia       VARCHAR(20) NOT NULL DEFAULT 'antes'
                            CHECK (estado_incidencia IN ('antes','durante','despues')),
    observaciones           TEXT DEFAULT NULL,
    tipo_foto               VARCHAR(20) NOT NULL DEFAULT 'aleatorio'
                            CHECK (tipo_foto IN ('aleatorio','comparativo')),
    secuencia_comparativa   INT DEFAULT NULL,
    nombre_archivo          VARCHAR(255) DEFAULT NULL,
    client_token            VARCHAR(64) DEFAULT NULL,
    es_visita_sin_foto      SMALLINT NOT NULL DEFAULT 0,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reg_infra ON registros (infra_id);
CREATE INDEX IF NOT EXISTS idx_reg_usuario ON registros (usuario_id);
CREATE INDEX IF NOT EXISTS idx_reg_fecha ON registros (fecha);
CREATE INDEX IF NOT EXISTS idx_reg_estado ON registros (estado_incidencia);
CREATE INDEX IF NOT EXISTS idx_reg_tipo_foto ON registros (tipo_foto);
CREATE INDEX IF NOT EXISTS idx_reg_unidad_obra ON registros (unidad_obra_id);
CREATE INDEX IF NOT EXISTS idx_reg_tipo_trabajo ON registros (tipo_trabajo_id);
CREATE INDEX IF NOT EXISTS idx_registros_infra_fecha ON registros (infra_id, fecha DESC);
CREATE INDEX IF NOT EXISTS idx_registros_infra_estado ON registros (infra_id, estado_incidencia);
CREATE INDEX IF NOT EXISTS idx_registros_usuario_fecha ON registros (usuario_id, fecha DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_registros_client_token ON registros (client_token) WHERE client_token IS NOT NULL;

-- -----------------------------------------------------------
-- 7. CAMPOS DE FORMULARIO (dinámicos por empresa)
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS campos_formulario (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      INT NOT NULL REFERENCES empresas (id) ON UPDATE CASCADE ON DELETE CASCADE,
    nombre          VARCHAR(150) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    tipo            VARCHAR(20) NOT NULL DEFAULT 'texto'
                    CHECK (tipo IN ('texto','numero','select','checkbox','textarea','fecha')),
    opciones        JSONB DEFAULT NULL,
    obligatorio     SMALLINT NOT NULL DEFAULT 0,
    orden           INT NOT NULL DEFAULT 0,
    activo          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_campo_empresa_slug ON campos_formulario (empresa_id, slug);
CREATE INDEX IF NOT EXISTS idx_campo_empresa ON campos_formulario (empresa_id);
CREATE INDEX IF NOT EXISTS idx_campo_orden ON campos_formulario (orden);

CREATE TRIGGER trg_campos_formulario_updated_at
    BEFORE UPDATE ON campos_formulario
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 8. VALORES DE CAMPO (por registro)
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS valores_campo (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id     INT NOT NULL REFERENCES registros (id) ON UPDATE CASCADE ON DELETE CASCADE,
    campo_id        INT NOT NULL REFERENCES campos_formulario (id) ON UPDATE CASCADE ON DELETE CASCADE,
    valor           TEXT DEFAULT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_valor_registro_campo ON valores_campo (registro_id, campo_id);
CREATE INDEX IF NOT EXISTS idx_valor_registro ON valores_campo (registro_id);
CREATE INDEX IF NOT EXISTS idx_valor_campo ON valores_campo (campo_id);
CREATE INDEX IF NOT EXISTS idx_valores_campo_registro ON valores_campo (registro_id);

-- -----------------------------------------------------------
-- 9. SUBIDAS FALLIDAS
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS subidas_fallidas (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id          INT NOT NULL REFERENCES empresas (id) ON DELETE CASCADE,
    usuario_id          INT NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    infra_id            INT NOT NULL REFERENCES infraestructuras (id) ON DELETE CASCADE,
    nombre_archivo      VARCHAR(255),
    estado_incidencia   VARCHAR(20) DEFAULT 'antes'
                        CHECK (estado_incidencia IN ('antes','durante','despues')),
    tipo_foto           VARCHAR(20) DEFAULT 'aleatorio'
                        CHECK (tipo_foto IN ('aleatorio','comparativo')),
    motivo_error        TEXT,
    intentos            INT DEFAULT 1,
    resuelta            SMALLINT DEFAULT 0,
    fecha_fallo         TIMESTAMP DEFAULT NOW(),
    fecha_resolucion    TIMESTAMP NULL,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sf_empresa ON subidas_fallidas (empresa_id);
CREATE INDEX IF NOT EXISTS idx_sf_usuario ON subidas_fallidas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sf_resuelta ON subidas_fallidas (resuelta);

-- -----------------------------------------------------------
-- 10. CAPAS KML
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS capas_kml (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      INT NOT NULL REFERENCES empresas (id) ON DELETE CASCADE,
    nombre          VARCHAR(255) NOT NULL,
    contenido_kml   TEXT NOT NULL,
    color           VARCHAR(7) DEFAULT '#8b5cf6',
    grosor          SMALLINT DEFAULT 3,
    opacidad        DECIMAL(3,2) DEFAULT 0.80,
    activa          SMALLINT DEFAULT 1,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ckml_empresa ON capas_kml (empresa_id);
CREATE INDEX IF NOT EXISTS idx_ckml_activa ON capas_kml (empresa_id, activa);

CREATE TRIGGER trg_capas_kml_updated_at
    BEFORE UPDATE ON capas_kml
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 11. CAPAS DE INFRAESTRUCTURAS (SHP/KML/KMZ → GeoJSON)
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS capas_infraestructuras (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      INT NOT NULL REFERENCES empresas (id),
    nombre          VARCHAR(255) NOT NULL,
    geojson         TEXT NOT NULL,
    campo_capa      VARCHAR(100) NOT NULL,
    campo_tabla     VARCHAR(100) NOT NULL DEFAULT 'codigo_unico',
    color           VARCHAR(7) DEFAULT '#e74c3c',
    grosor          SMALLINT DEFAULT 2,
    opacidad        DECIMAL(3,2) DEFAULT 0.80,
    activa          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ci_empresa ON capas_infraestructuras (empresa_id);

CREATE TRIGGER trg_capas_infraestructuras_updated_at
    BEFORE UPDATE ON capas_infraestructuras
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- 12. PUNTOS DE MAPA
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS puntos_mapa (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      INT NOT NULL REFERENCES empresas (id) ON DELETE CASCADE,
    nombre          VARCHAR(200) NOT NULL,
    descripcion     TEXT NULL,
    lat             DECIMAL(10,7) NOT NULL,
    lon             DECIMAL(10,7) NOT NULL,
    icono           VARCHAR(50) NOT NULL DEFAULT 'pin',
    color           VARCHAR(20) NOT NULL DEFAULT '#e74c3c',
    activo          SMALLINT NOT NULL DEFAULT 1,
    created_by      INT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pm_empresa ON puntos_mapa (empresa_id);
CREATE INDEX IF NOT EXISTS idx_pm_activo ON puntos_mapa (empresa_id, activo);

CREATE TRIGGER trg_puntos_mapa_updated_at
    BEFORE UPDATE ON puntos_mapa
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- -----------------------------------------------------------
-- VISTA: aislamiento multi-tenant
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW v_registros_empresa AS
SELECT
    r.id            AS registro_id,
    r.fecha,
    r.lat_real,
    r.lon_real,
    r.url_cloudinary,
    r.datos_tecnicos,
    r.estado_incidencia,
    r.observaciones,
    i.id            AS infra_id,
    i.nombre        AS infra_nombre,
    i.codigo_unico,
    i.lat_teorica,
    i.lon_teorica,
    u.id            AS usuario_id,
    u.nombre        AS usuario_nombre,
    u.email         AS usuario_email,
    e.id            AS empresa_id,
    e.nombre        AS empresa_nombre,
    e.plan_suscripcion
FROM registros r
    INNER JOIN infraestructuras i ON r.infra_id   = i.id
    INNER JOIN usuarios u         ON r.usuario_id = u.id
    INNER JOIN empresas e         ON i.empresa_id = e.id;

-- -----------------------------------------------------------
-- Seed: empresa TRAGSA + superadmin
-- -----------------------------------------------------------
INSERT INTO empresas (id, nombre, plan_suscripcion, email_contacto, activa, licencia_inicio, licencia_fin, max_usuarios, max_infraestructuras)
VALUES (9999, 'INFOCAMPO Platform', 'enterprise', 'admin@infocampo.app', 1, '2024-01-01', '2099-12-31', 999, 9999)
ON CONFLICT (id) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO usuarios (empresa_id, nombre, email, password, rol, activo)
VALUES (9999, 'Super Administrador', 'superadmin@infocampo.app',
        '$2y$12$.H/lthGtzLS8IijNMp1ICOQgi7t7EzyJSbwbwUDs/yP5EjPGHJXYW',
        'superadmin', 1)
ON CONFLICT DO NOTHING;
